import 'package:flutter/material.dart';
import 'package:flutter/services.dart';
import 'package:flutter_svg/flutter_svg.dart';
import 'package:rajanigandha/utils/base/base_screen.dart';

import '../utils/images.dart';

class PrivacyPolicyScreen extends StatelessWidget {
  const PrivacyPolicyScreen({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return BaseScreen(
      title: "Privacy Policy",
      body: Column(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          Expanded(
            child: SingleChildScrollView(
              padding: EdgeInsets.all(20),
              child: Column(
                crossAxisAlignment: CrossAxisAlignment.start,
                children: [
                  _buildSectionTitle('PRIVACY NOTICE'),
                  SizedBox(height: 12),
                  _buildParagraph(
                    'Your privacy is important to us and hence it is important for you to know what personal information we collect from you and third parties about you, how we collect it, where all do we use it and also some of the rights that you are entitled to as a data subject.',
                  ),
                  SizedBox(height: 16),
                  _buildSectionTitle('Privacy Policy'),
                  SizedBox(height: 12),
                  _buildParagraph(
                    'This Privacy Policy is an electronic record under the Information Technology Act, 2000, Digital Personal Data Protection Act, 2023, and the rules made thereunder and the provisions pertaining to electronic records in various statutes as amended by the Information Technology Act, 2000, from time to time. This electronic record is generated by a computer system and does not require any physical or digital signatures to make the terms of this Privacy Policy binding.',
                  ),
                  SizedBox(height: 12),
                  _buildParagraph(
                    'This Privacy Policy is published under the requirements specified by the Information Technology (Reasonable security practices and procedures and sensitive personal data or information) Rules, 2011, made under the Information Technology Act, 2000.',
                  ),
                  SizedBox(height: 16),
                  _buildSectionTitle('SCOPE'),
                  SizedBox(height: 12),
                  _buildParagraph(
                    'This Privacy Policy ("Policy") applies to the information collected and used by Dharampal Satyapal Limited on its website business.rajingandha.com.',
                  ),
                  SizedBox(height: 12),
                  _buildParagraph(
                    'This privacy statement applies to business.rajnigandha.com ​, as well as other “sub-domains” or “microsites” including MasterStroke.Rajnigandha.com, Scheme.Rajnigandha.com.',
                  ),
                  SizedBox(height: 12),
                  _buildParagraph(
                      'Dharampal Satyapal Limited which includes its associates, affiliates, group companies, and subsidiary (ies) unless the context clearly provides otherwise. As used in this policy, member (whether registered or not) shall be referred to as "you", "your" and "yourself" which shall mean any natural or legal person who is accessing the website, its contents and using the services offered on or through the website.',
                  ),
                  SizedBox(height: 12),
                  _buildParagraph(
                    'The website recognizes the importance of maintaining your privacy. We value your privacy and appreciate your trust in us. This policy describes how we treat information we collect from you. By visiting and/or using our website, you agree to the terms of this Privacy Policy. If you do not agree please do not use or access our website.',
                  ),
                  SizedBox(height: 16),
                  _buildSectionTitle('INFORMATION WE COLLECT'),
                  SizedBox(height: 16),
                  _buildSectionTitle('Identifiable Information:'),
                  SizedBox(height: 12),
                  _buildParagraph(
                    'There are a number of situations in which your personal information may be collected by us in order to serve you better. At various touch points, we may collect the following personal information including but not limited to your name, address, contact information, date of birth, anniversary date, educational details, income details, occupational details, marital status, gender, and consumption pattern/details of Rajnigandha Pan Masala. Besides the aforesaid personal information, we may also collect:',
                  ),
                  SizedBox(height: 12),
                  _buildParagraph(
                    '• User name, membership number and password made by you when you register at our website or become a member of our loyalty program/trade scheme/promotions through the website or its subdomains/microsites.',
                  ),
                  SizedBox(height: 12),
                  _buildParagraph(
                    '• Your transaction history, unique codes used for points updation and redemption.',
                  ),
                  SizedBox(height: 12),
                  _buildYourQuery(
                    '• Your queries, comments and complaints.',
                  ),
                  SizedBox(height: 12),
                  _buildParagraph(
                    '• You may, however, visit our website anonymously. We will collect personally identifiable information from you only if you voluntarily submit such information to us. You can always refuse to provide personally identifiable information, but by doing so, you may be prevented from engaging in website related activities. You can always refuse to provide personally identifiable information, but by doing so, you may be prevented from engaging in website related activities.',
                  ),
                  SizedBox(height: 16),
                  _buildSectionTitle('Identifiable Information:Non- Personally Identifiable Information:'),
                  SizedBox(height: 12),
                  _buildParagraph(
                    'We may collect non- personally identifiable information from you whenever you interact with our website. Non- personally identifiable information may include your IP address and the browser using. We might look at what site you came from, duration of time spent on our website, pages accessed or what site you visit when you leave our website. We might also collect the type of mobile device you are using, or the version of the operating system your computer or device is running and other similar information.',
                  ),
                  SizedBox(height: 16),
                  _buildSectionTitle('You hereby represent to us :'),
                  SizedBox(height: 12),
                  _buildParagraph(
                    'The information you provide to us from time to time is and shall be authentic, correct, current and updated and you have all the rights, permissions and consents, as may be required, to provide such information to us.You are providing the information to us and our consequent storage, collection, usage, transfer, access or processing of the same shall not be in violation of any applicable laws, third party agreement, judgments, orders and court decrees.We and each of our representatives, officers, directors, contractors and agents shall not be responsible for the authenticity of the information that you provide to us. You shall indemnify and hold us harmless and each of our officers, directors, contractors, agents or any third party relying on the information provided by you in the event:-(i) you are in breach of this policy including this provision and the immediately preceding provision; and (ii) any suit, action or claim is brought against us by any third party with respect to the information provided by you to us.',
                  ),
                  SizedBox(height: 16),
                  _buildSectionTitle('HOW DO WE USE YOUR INFORMATION'),
                  SizedBox(height: 12),
                  _buildParagraph(
                    'We may use the information collected from you at the time of your visit on our site and register for our loyalty program, sign up for our promotions, respond to a survey or marketing communication or use certain other site features in the following ways:',
                  ),
                ],
              ),
            ),
          ),
        ],
      ),
    );
  }

  Widget _buildSectionTitle(String title) {
    return Text(
      title,
      style: TextStyle(
        fontSize: 18,
        fontWeight: FontWeight.w700,
        color: Colors.white,
        letterSpacing: 1.2,
      ),
    );
  }

  Widget _buildParagraph(String text) {
    return Text(
      text,
      style: TextStyle(
        fontSize: 16,
        color: Colors.white70,
        height: 1.5,
      ),
      textAlign: TextAlign.justify,
    );
  }

  Widget _buildYourQuery(String text) {
    return Text(
      text,
      style: TextStyle(
        fontSize: 16,
        color: Colors.white70,
        height: 1.5,
      ),
      // textAlign: TextAlign.justify,
    );
  }

}
